# Generated by Django 5.0 on 2023-12-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('clietn_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('born_date', models.DateField()),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.invoice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.product')),
            ],
        ),
    ]
